name: Dev - Deploy API Shop

on:
    push:
      branches:
        - dev
      paths-ignore:
        - 'README.md'
        - '.github/**'
        - '.gitignore'
    workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    name: Dev Deploy
    environment: dev

    steps:
      - name: Check out code
        uses: actions/checkout@v5

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::${{ secrets.DEV_AWS_ACCOUNT }}:role/GithubActionsRole
          role-session-name: github-actions

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build and prepare deployment
        run: |
          chmod +x build.sh
          bash build.sh

      - name: Install zip tool
        if: success()
        uses: montudor/action-zip@v1

      - name: Create Zip file for Lambda function
        if: success()
        run: |
          cd dist
          zip -r ../code.zip *

      - name: Update Lambda function code
        if: success()
        uses: imehedi/actions-awscli-v2@latest
        with:
            args: "lambda update-function-code \
                --function-name arn:aws:lambda:eu-west-2:${{ secrets.DEV_AWS_ACCOUNT }}:function:API-Shop \
                --zip-file fileb://code.zip"

      - name: Wait for function update to complete
        if: success()
        run: sleep 10
      
      - name: Update Lambda environment variables
        if: success()
        uses: imehedi/actions-awscli-v2@latest
        with:
            args: "lambda update-function-configuration \
                --function-name arn:aws:lambda:eu-west-2:${{ secrets.DEV_AWS_ACCOUNT }}:function:API-Shop \
                --environment Variables='{TABLE_NAME=Shop}'"